#! /usr/bin/env php

<?php

$autoloadPath1 = __DIR__ . '/vendor/autoload.php';
$autoloadPath2 = __DIR__ . '/../../autoload.php';

if (file_exists($autoloadPath1)) {
    require_once $autoloadPath1;
} else {
    require_once $autoloadPath2;
}

$doc = <<<DOC
Generate diff

Usage: 
gendiff (-h|--help)
gendiff --version

Options:
-h|--help  Show help screen
--version  Show version
DOC;

$args = Docopt::handle($doc, ['version' => 'Generate diff v.0.1']);